// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "AppleDevelopmentFoundation",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "AppFoundation", targets: ["AppFoundation"]),
        .library(name: "DesignSystem", targets: ["DesignSystem"]),
        .library(name: "FormKit", targets: ["FormKit"]),
        .library(name: "OnboardingKit", targets: ["OnboardingKit"]),
        .library(name: "NavigationKit", targets: ["NavigationKit"]),
        .library(name: "PersistenceKit", targets: ["PersistenceKit"]),
        .library(name: "FileKit", targets: ["FileKit"]),
        .library(name: "MediaKit", targets: ["MediaKit"]),
        .library(name: "FeedbackKit", targets: ["FeedbackKit"]),
        .library(name: "LoggingKit", targets: ["LoggingKit"]),
        .library(name: "AppShellKit", targets: ["AppShellKit"]),
    ],
    targets: [
        .target(name: "AppFoundation"),
        .target(name: "DesignSystem"),
        .target(name: "FormKit", dependencies: ["DesignSystem"]),
        .target(name: "OnboardingKit", dependencies: ["DesignSystem"]),
        .target(name: "NavigationKit"),
        .target(name: "PersistenceKit"),
        .target(name: "FileKit"),
        .target(name: "MediaKit", dependencies: ["FileKit"]),
        .target(name: "FeedbackKit", dependencies: ["DesignSystem"]),
        .target(name: "LoggingKit"),
        .target(name: "AppShellKit"),
        .executableTarget(name: "FoundationGallery", dependencies: ["DesignSystem", "FormKit", "FeedbackKit", "OnboardingKit"], path: "Examples/FoundationGallery"),
        .executableTarget(name: "iOSExample", dependencies: ["DesignSystem", "FormKit"], path: "Examples/iOSExample"),
        .executableTarget(name: "macOSExample", dependencies: ["DesignSystem", "AppShellKit"], path: "Examples/macOSExample"),
        .target(name: "TestingSupport", dependencies: ["AppFoundation"], path: "Tests/TestingSupport"),
        .testTarget(name: "AppFoundationTests", dependencies: ["AppFoundation", "TestingSupport"]),
        .testTarget(name: "DesignSystemTests", dependencies: ["DesignSystem"]),
        .testTarget(name: "FormKitTests", dependencies: ["FormKit"]),
        .testTarget(name: "OnboardingKitTests", dependencies: ["OnboardingKit"]),
        .testTarget(name: "NavigationKitTests", dependencies: ["NavigationKit"]),
        .testTarget(name: "PersistenceKitTests", dependencies: ["PersistenceKit"]),
        .testTarget(name: "FileKitTests", dependencies: ["FileKit", "TestingSupport"]),
        .testTarget(name: "FeedbackKitTests", dependencies: ["FeedbackKit"]),
        .testTarget(name: "MediaKitTests", dependencies: ["MediaKit", "TestingSupport"]),
        .testTarget(name: "LoggingKitTests", dependencies: ["LoggingKit"]),
        .testTarget(name: "AppShellKitTests", dependencies: ["AppShellKit"]),
    ]
)
